version: '3'
services:
  frontend:
    build:
      context: PollBuddy-Server/frontend
      dockerfile: "Dockerfile.lint"

  backend:
    build:
      context: PollBuddy-Server/backend
      dockerfile: "Dockerfile.lint"