FROM node:16

WORKDIR /usr/src/app

COPY package*.json ./

RUN npm install

COPY bin ./bin

COPY models ./models

COPY modules ./modules

COPY public ./public

COPY routes ./routes

COPY app.js ./

COPY .env* ./

RUN ["mv","-n", ".env.example", ".env"]

COPY .eslint* ./

COPY jest.config.js ./

COPY jest-mongodb-config.js ./

ENV JEST=true

CMD ["sh", "-c", "echo 'Running backend tests:'; npm run test"]
