FROM node:16-stretch

# Create app directory
WORKDIR /usr/src/app

# Install app dependencies
# A wildcard is used to ensure both package.json AND package-lock.json are copied
# where available (npm@5+)
COPY package*.json ./

RUN npm install

# Bundle app source
# Folders
COPY bin ./bin
COPY models ./models
COPY modules ./modules
COPY public ./public
COPY routes ./routes
# Files
COPY app.js ./
COPY .env ./
COPY .eslint* ./
COPY jest.config.js ./
COPY jest-mongodb-config.js ./

# Start command
CMD ["sh", "-c", "echo 'Running backend tests:'; npm run test"]
