FROM node:16

WORKDIR /usr/src/app

COPY package*.json ./

RUN npm install

COPY public ./public

COPY src ./src

COPY .env* ./

RUN ["mv","-n", ".env.example", ".env"]

COPY .eslint* ./

COPY babel.config.js ./

COPY jest.config.js ./

CMD ["sh", "-c", "echo 'Running frontend tests:' ; npm run test"]
