# SecretMap to store the secret backend details
---
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: poll-buddy-backend-secrets-master
  labels:
    app.kubernetes.io/name: poll-buddy-backend
    app.kubernetes.io/component: backend
    app.kubernetes.io/part-of: poll-buddy
    app.kubernetes.io/instance: "master"
    app: poll-buddy-backend
    environment: production
    dev_instance_type: no-type
    dev_instance_id: "no-id"
data:
  # This should be changed
  session_secret: TlRwVWtENnh5QUxxNExNQjJGREhmMmlLZFljU3pubnM=
