# Create a service to access the deployment pods
---
apiVersion: v1
kind: Service
metadata:
  name: poll-buddy-reporting-service-master
  labels:
    app.kubernetes.io/name: poll-buddy-reporting-service-master
    app.kubernetes.io/component: reporting
    app.kubernetes.io/part-of: poll-buddy
    app.kubernetes.io/instance: "master"
    app: poll-buddy-reporting
    environment: production
    dev_instance_type: no-type
    dev_instance_id: "no-id"
spec:
  ports:
    - port: 3000
      protocol: TCP
      targetPort: reporting
  selector:
    app.kubernetes.io/name: poll-buddy-reporting
    app.kubernetes.io/component: reporting
    app.kubernetes.io/part-of: poll-buddy
    app.kubernetes.io/instance: "master"
    app: poll-buddy-reporting
    environment: production
    dev_instance_type: no-type
    dev_instance_id: "no-id"
  type: ClusterIP

# Create a deployment to run in
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: poll-buddy-reporting-deployment-master
  labels:
    app.kubernetes.io/name: poll-buddy-reporting
    app.kubernetes.io/component: reporting
    app.kubernetes.io/part-of: poll-buddy
    app.kubernetes.io/instance: "master"
    app: poll-buddy-reporting
    environment: production
    dev_instance_type: no-type
    dev_instance_id: "no-id"
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: poll-buddy-reporting
      app.kubernetes.io/component: reporting
      app.kubernetes.io/part-of: poll-buddy
      app.kubernetes.io/instance: "master"
      app: poll-buddy-reporting
      environment: production
      dev_instance_type: no-type
      dev_instance_id: "no-id"
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app.kubernetes.io/name: poll-buddy-reporting
        app.kubernetes.io/component: reporting
        app.kubernetes.io/part-of: poll-buddy
        app.kubernetes.io/instance: "master"
        app: poll-buddy-reporting
        environment: production
        dev_instance_type: no-type
        dev_instance_id: "no-id"
    spec:
      restartPolicy: Always
      containers:
        - image: pollbuddy/reporting:latest
          imagePullPolicy: Always
          name: reporting
          ports:
            - containerPort: 3000
              name: reporting
          env:
            - name: REPORTING_DB_URL
              value: poll-buddy-reporting-db-service-master
            - name: REPORTING_DB_NAME
              valueFrom:
                configMapKeyRef:
                  name: poll-buddy-reporting-db-configmap-master
                  key: reporting_db_name
            - name: REPORTING_DB_USERNAME
              valueFrom:
                configMapKeyRef:
                  name: poll-buddy-reporting-db-configmap-master
                  key: reporting_db_username
            - name: REPORTING_DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: poll-buddy-reporting-db-secrets-master
                  key: user-password
          # Probes to report the status of the application
          startupProbe: # Runs to know when the app started up
            httpGet:
              path: /
              port: reporting
              scheme: HTTP
            failureThreshold: 10
            periodSeconds: 5
            successThreshold: 1
            timeoutSeconds: 1
            initialDelaySeconds: 5
          readinessProbe: # Runs to make sure the app is ready to receive requests
            httpGet:
              path: /
              port: reporting
              scheme: HTTP
            failureThreshold: 2
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 3
            initialDelaySeconds: 5
          livenessProbe: # Runs to make sure the app is alive
            httpGet:
              path: /
              port: reporting
              scheme: HTTP
            failureThreshold: 2
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 5
            initialDelaySeconds: 5
