# ConfigMap to store the non-secret reporting database details
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: poll-buddy-reporting-db-configmap-master
  labels:
    app.kubernetes.io/name: poll-buddy-reporting
    app.kubernetes.io/component: reporting
    app.kubernetes.io/part-of: poll-buddy
    app.kubernetes.io/instance: "master"
    app: poll-buddy-reporting
    environment: production
    dev_instance_type: no-type
    dev_instance_id: "no-id"
data:
  reporting_db_name: pollbuddy
  reporting_db_admin_username: root
  reporting_db_username: pollbuddy
