name: Test

on:
  push:

jobs:
  frontend-test:
    name: Frontend Test
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Docker Build
        working-directory: ./PollBuddy-Server/frontend
        run: docker build . --file Dockerfile.test -t frontend-test
      - name: Docker Run
          working-directory: ./PollBuddy-Server/frontend
          run: docker run frontend-test

  backend-test:
    name: Backend Test
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Docker Build
          working-directory: ./PollBuddy-Server/backend
          run: docker build . --file Dockerfile.test -t backend-test
      - name: Docker Run
          working-directory: ./PollBuddy-Server/backend
          run: docker run backend-test

